name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build and tag Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/fastapi-app:latest .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/$PROJECT_ID/fastapi-app:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/fastapi-app:latest \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated

    - name: Verify Deployment
      run: |
        gcloud run services describe $SERVICE_NAME --region $REGION
