
name: CI/CD Pipeline for GCP Cloud Run

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Set GCP Project and Region
      - name: Configure GCP
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1 # Change region if needed

      # Step 4: Build and Push Docker Image to Artifact Registry
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-repo/my-app:latest
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-repo/my-app:latest
          gcloud run deploy my-cloud-run-service \
            --image $IMAGE_NAME \
            --platform managed \
            --allow-unauthenticated
